apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ffmpeg\bin\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ffmpeg\bin\kompose.exe convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/my-react-imageboard-node-network: "true"
        io.kompose.network/my-react-imageboard-postgres: "true"
        io.kompose.service: backend
    spec:
      containers:
        - image: backend
          name: backend-container
          ports:
            - containerPort: 7000
              hostPort: 7005
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
