apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ffmpeg\bin\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  ports:
    - name: "7005"
      port: 7005
      targetPort: 7000
  selector:
    io.kompose.service: backend
status:
  loadBalancer: {}
