apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ffmpeg\bin\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 80
  selector:
    io.kompose.service: nginx
status:
  loadBalancer: {}
