apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ffmpeg\bin\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: pgadmin
  name: pgadmin
spec:
  ports:
    - name: "90"
      port: 90
      targetPort: 80
  selector:
    io.kompose.service: pgadmin
status:
  loadBalancer: {}
