apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ffmpeg\bin\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  ports:
    - name: "5435"
      port: 5435
      targetPort: 5432
  selector:
    io.kompose.service: postgres
status:
  loadBalancer: {}
